### ISSUE TITLE
Enable compilation with MVSC

### ISSUE THREAD

**Issue by jdupak** [cvut/qtrvsim#101]

**Comment by MatejKafka** [comment]
Notes for later from my experiments:

- Currently, only MinGW is supported on Windows, and existing releases are 32bit (which is unfortunate). The advantage is that MinGW tries to emulate parts of POSIX, which is used in the os_emulation module.
- MSVC support seems a bit restrictive, probably not worth it.
- Clang support on Windows seems quite doable, biggest blocker is that os_emulation uses POSIX I/O syscalls, which will need to be emulated, either by using an existing library or DIY. Other changes were simple, already done in https://github.com/MatejKafka/qtrvsim-pr/. Otherwise, Clang aims for ABI compatibility with MSVC, so the MSVC version of Qt can be used.

**Comment by jdupak** [comment]
Resolved by #104
