### ISSUE TITLE
Bug: UnsupportedInstruction

### ISSUE THREAD

**Issue by ArielHeleneto** [cvut/qtrvsim#96]
Press "Start Empty" Buttom, you get Figure 1 who have a tons of "Unknown".

![Figure 1](https://github.com/cvut/qtrvsim/assets/32459390/a5135c4d-0b06-4f95-a77a-01705d0ea79a)

Then press "Run" Buttom, it says "UnsupportedInstruction" seen on Figure 2.

![Figure 2](https://github.com/cvut/qtrvsim/assets/32459390/92c2bb1d-c076-482b-862c-ec85b8eb62e8)

Successfully reproduced on [v0.9.6](https://github.com/cvut/qtrvsim/releases/tag/v0.9.6). [v0.9.5](https://github.com/cvut/qtrvsim/releases/tag/v0.9.5) works fine.

**Comment by ppisa** [comment]
If you extend instruction area then you can see that unfilled memory content is sequence of zero values (0x00000000). This is intentional that RISC-V ISA does not use this code for valid instruction. So running such memory sequence causes exception. You need to write program and compile it the first.  The Example button does that for you to start from some code for demonstration.
